# Generated by Django 4.1.3 on 2022-11-04 04:08


from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('content', models.TextField(null=True)),
                ('tag', models.CharField(max_length=50, null=True)),
                ('country', models.CharField(max_length=30, null=True)),
                ('image', models.TextField(null=True)),
            ],
        ),
    ]
