# Generated by Django 4.1.3 on 2022-11-06 06:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('content', models.TextField(null=True)),
                ('tag', models.CharField(max_length=50, null=True)),
                ('country', models.CharField(max_length=30, null=True)),
                ('taster_name', models.CharField(max_length=20, null=True)),
                ('grade', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('image', models.TextField(null=True)),
            ],
        ),
    ]
