# Generated by Django 4.1.3 on 2022-11-02 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0002_alter_tweet_content_alter_tweet_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='country',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='tag',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
