# Generated by Django 4.1.3 on 2022-11-02 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0003_alter_tweet_content_alter_tweet_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='image',
            field=models.TextField(null=True),
        ),
    ]
